### ISSUE TITLE
Are there any plans for a docker image with latest version?

### ISSUE THREAD

**Issue by Locustv2** [evilru/quake3-vsp-stats#8]
Hey, i am trying to find a stats processor for my server running on quakejs. It seems that the latest version of vsp is 0.50. Are you planning to have an update for that?

Also would it be possible to dockerize it so we can just use the image?

**Comment by evilru** [comment]
Hello!

The version I maintain here contains a fix to support https://www.excessiveplus.net/.
It only contains the q3a media files.
For more details, please have a look at the [readme-xp.txt](https://github.com/evilru/quake3-vsp-stats/blob/master/readme-xp.txt).

I only maintain compatibility to current php / db versions.

A docker image is a good idea :).

Actually, I have a docker-compose setup for testing in the [php8 branch](https://github.com/evilru/quake3-vsp-stats/tree/php8/docker).

Let me think about a possible setup and the required vsp configuration settings.

**Comment by Locustv2** [comment]
Does the version that you maintain works with regular baseq3 or other mods on quake?

**Comment by evilru** [comment]
Yes, it should work with most mods.
I use it with osp and ra3.

The baseq3 version has a limitation: https://github.com/evilru/quake3-vsp-stats/issues/5

As you asked about a Dockerimage, I just started on it and have a first work in progress version ready: https://github.com/evilru/quake3-vsp-stats/tree/dockerimage

**Comment by Locustv2** [comment]
Cool. the link you provided is a 404 on my side.

**Comment by evilru** [comment]
Hello, maybe you would like to try this first version of the [docker-compose stack](https://github.com/evilru/quake3-vsp-stats/tree/dev).

You should find everything you need in the readme.
I will put the Image on dockerhub in the next days.

Please let me know if something does not work for you or if the documentation is hard to understand.

**Comment by Locustv2** [comment]
I'll try that hopefully tonight and let you know. thanks

**Comment by Locustv2** [comment]
Cool, i managed to do a test.

First test i just spawn the container with the original docker-compose you provided and i added just the volume for the `games.log`

Game was running and  i waited several minutes but nothing on the page.

Then i added the Environment variables for `LOGTYPE` as well as `DB_HOSTNAME` and it seem to works.
However i noticed that when i go to localhost on my browser, it redirects me to: http://localhost/pub/themes/bismarck/index.php?
Is that normal.

Also, is there a way to set the default theme? And if possible parse more than 1 games.log?
Or the only way would be to modify the `/vsp/docker/import.sh`?

Here is my docker-compose template:

```
version: '3.3'

services:
  db:
    # image: mysql:8.0.23
    image: mariadb:10.5.9
    restart: always
    environment:
      TZ: Europe/Berlin
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: vsp
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "3306:3306"
  web:
    image: evilru/quake3-vsp-stats:latest
    restart: always
    depends_on:
      - db
    volumes:
      # - /path/to/your/games.log:/vsp/games.log
      # - /path/to/your/server.gif:/vsp/pub/images/server.gif
      # - /path/to/your/logo.gif:/vsp/pub/images/logo.gif
      - ./customcfg/lms.log:/vsp/games.log
    ports:
      - 8081:80
      # supervisor web gui would be available on port 9001
      - 9001:9001
    environment:
      TZ: Europe/Berlin
      # VSP_WEB_PASSWORD: vspweb
      DB_HOSTNAME: db
      DB_NAME: vsp
      DB_USERNAME: devuser
      DB_PASSWORD: devpass
      LOGTYPE: q3a

```
